In [1]:
import torch
import pytorch_lightning as pl
import torchvision
from matplotlib import pyplot as plt
import numpy as np
from torch.nn import functional as F
from torch import nn
import advertorch as at
from pytorch_lightning.loggers import TensorBoardLogger
import foolbox as fb
from CIFARCLassifier import CIFARCLassifier


In [2]:
print(torch.cuda.is_available())


True


In [3]:
model = CIFARCLassifier()

In [4]:
model.prepare_data()
logger = TensorBoardLogger('tb_logs', name="adversarial_cifar10_model")
model.train_dataloader()
trainer = pl.Trainer(max_epochs=2, logger=logger, gpus=[0], fast_dev_run=False)

GPU available: True, used: True
TPU available: False, using: 0 TPU cores
CUDA_VISIBLE_DEVICES: [0]


In [5]:
trainer.fit(model)


   | Name    | Type        | Params
-----------------------------------------
0  | conv1   | Conv2d      | 2 K   
1  | bn1     | BatchNorm2d | 64    
2  | pool    | MaxPool2d   | 0     
3  | conv2   | Conv2d      | 12 K  
4  | bn2     | BatchNorm2d | 32    
5  | conv3   | Conv2d      | 12 K  
6  | bn3     | BatchNorm2d | 64    
7  | flatten | Flatten     | 0     
8  | fc1     | Linear      | 65 K  
9  | do1     | Dropout     | 0     
10 | fc2     | Linear      | 1 K   


10000
Successful attack:8647 Attack count:10000 Percentage:0.8647


10000
Successful attack:4084 Attack count:10000 Percentage:0.4084


10000
Saving latest checkpoint..
Successful attack:3562 Attack count:10000 Percentage:0.3562



1

In [6]:
model.adversarial_validation()

10000
Successful attack:3562 Attack count:10000 Percentage:0.3562


64.38

you can get the values of the named parameters with print(list(model.conv1.named_parameters()))

In [7]:
print(list(model.conv1.named_parameters()))

[('weight', Parameter containing:
tensor([[[[-9.2531e-02, -1.1092e-01, -8.9914e-02,  3.7625e-02, -4.6159e-02],
          [ 9.4196e-02, -1.1945e-01, -3.2949e-02,  1.5200e-01, -1.2732e-04],
          [ 1.2444e-01, -4.4742e-02, -8.6356e-02,  1.0605e-01, -2.8258e-02],
          [-1.2235e-02, -1.1799e-01, -1.7161e-01,  1.8011e-01, -1.4800e-01],
          [-6.5543e-02,  9.6769e-02, -6.6543e-02,  4.7016e-02, -5.9040e-02]],

         [[ 1.4739e-01, -1.4507e-03, -4.4452e-02,  8.6980e-02,  8.6316e-03],
          [ 5.6593e-02,  2.9457e-02,  1.4238e-01,  8.6065e-02, -4.6510e-02],
          [ 5.9029e-02,  8.4570e-02,  3.6732e-02,  1.3732e-01,  3.5968e-02],
          [ 8.7225e-02, -1.2473e-01,  3.5441e-02,  2.4525e-01, -1.0805e-01],
          [-8.6720e-02,  1.1490e-01,  3.7145e-02,  1.1837e-01, -1.3768e-01]],

         [[ 7.1951e-02,  9.3405e-02, -1.2396e-01,  2.0572e-02,  5.4072e-02],
          [-2.2805e-02, -1.3054e-01,  8.3805e-02,  9.4242e-02, -6.0547e-02],
          [ 5.9537e-02, -4.5134e-02, -

In [8]:
model.perform_pruning()

In [9]:
print(list(model.conv1.named_parameters()))

[('weight', Parameter containing:
tensor([[[[-9.2531e-02, -1.1092e-01, -8.9914e-02,  3.7625e-02, -4.6159e-02],
          [ 9.4196e-02, -1.1945e-01, -3.2949e-02,  1.5200e-01, -1.2732e-04],
          [ 1.2444e-01, -4.4742e-02, -8.6356e-02,  1.0605e-01, -2.8258e-02],
          [-1.2235e-02, -1.1799e-01, -1.7161e-01,  1.8011e-01, -1.4800e-01],
          [-6.5543e-02,  9.6769e-02, -6.6543e-02,  4.7016e-02, -5.9040e-02]],

         [[ 1.4739e-01, -1.4507e-03, -4.4452e-02,  8.6980e-02,  8.6316e-03],
          [ 5.6593e-02,  2.9457e-02,  1.4238e-01,  8.6065e-02, -4.6510e-02],
          [ 5.9029e-02,  8.4570e-02,  3.6732e-02,  1.3732e-01,  3.5968e-02],
          [ 8.7225e-02, -1.2473e-01,  3.5441e-02,  2.4525e-01, -1.0805e-01],
          [-8.6720e-02,  1.1490e-01,  3.7145e-02,  1.1837e-01, -1.3768e-01]],

         [[ 7.1951e-02,  9.3405e-02, -1.2396e-01,  2.0572e-02,  5.4072e-02],
          [-2.2805e-02, -1.3054e-01,  8.3805e-02,  9.4242e-02, -6.0547e-02],
          [ 5.9537e-02, -4.5134e-02, -

In [10]:
print(list(model.conv1.named_buffers()))

[]


In [11]:
model.adversarial_validation()

10000


RuntimeError: Only Tensors created explicitly by the user (graph leaves) support the deepcopy protocol at the moment

In [12]:
list(model.fc2.weight.grad)

[tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0.]),
 tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0.,