In [1]:
import torch
import pytorch_lightning as pl
import torchvision
from matplotlib import pyplot as plt
import numpy as np
from torch.nn import functional as F
from torch import nn
import advertorch as at
from pytorch_lightning.loggers import TensorBoardLogger
import foolbox as fb
from CIFARCLassifier import CIFARCLassifier

In [2]:
print(torch.cuda.is_available())

True


In [3]:
model = CIFARCLassifier()

/opt/conda/lib/python3.7/site-packages/foolbox/models/pytorch.py:37: UserWarning: The PyTorch model is in training mode and therefore might not be deterministic. Call the eval() method to set it in evaluation mode if this is not intended.
  "The PyTorch model is in training mode and therefore might"


In [4]:
model.prepare_data()
logger = TensorBoardLogger('tb_logs', name="adversarial_cifar10_model")
model.train_dataloader()
trainer = pl.Trainer(max_epochs=2, logger=logger, gpus=[0], fast_dev_run=False)

GPU available: True, used: True
TPU available: False, using: 0 TPU cores
CUDA_VISIBLE_DEVICES: [0]


In [5]:
trainer.fit(model)


   | Name    | Type        | Params
-----------------------------------------
0  | conv1   | Conv2d      | 2 K   
1  | bn1     | BatchNorm2d | 64    
2  | pool    | MaxPool2d   | 0     
3  | conv2   | Conv2d      | 12 K  
4  | bn2     | BatchNorm2d | 32    
5  | conv3   | Conv2d      | 12 K  
6  | bn3     | BatchNorm2d | 64    
7  | flatten | Flatten     | 0     
8  | fc1     | Linear      | 65 K  
9  | do1     | Dropout     | 0     
10 | fc2     | Linear      | 1 K   


10000
Successful attack:9000 Attack count:10000 Percentage:0.9


10000
Successful attack:9000 Attack count:10000 Percentage:0.9
Saving latest checkpoint..



1

In [6]:
model.adversarial_validation()

10000
Successful attack:8566 Attack count:10000 Percentage:0.8566


14.339999999999996

you can get the values of the named parameters with print(list(model.conv1.named_parameters()))

In [7]:
print(list(model.conv1.named_parameters()))

[('weight', Parameter containing:
tensor([[[[ 8.7982e-02,  8.5622e-02,  7.1099e-02,  4.3684e-02,  2.9080e-02],
          [ 6.7263e-02,  7.0992e-02,  9.9368e-02,  7.5297e-02,  8.3281e-02],
          [ 1.0704e-01,  7.3422e-02, -4.9580e-02,  1.2928e-01,  1.2822e-01],
          [-6.6067e-03,  7.1147e-02, -7.1086e-02, -9.3603e-03, -2.9341e-02],
          [ 1.2063e-01, -3.8537e-02, -7.5647e-02,  1.0389e-01, -8.6257e-02]],

         [[-8.4184e-02,  7.5236e-02,  8.4671e-02, -1.9000e-02,  4.6655e-02],
          [ 1.2659e-01,  5.6393e-02, -6.3011e-02,  8.5046e-03, -7.7577e-02],
          [ 4.9156e-02,  1.2315e-01, -7.4491e-02,  1.3343e-01, -2.4807e-02],
          [-2.7209e-02, -4.6297e-03,  1.4453e-01, -1.7301e-02, -8.6515e-02],
          [ 1.4329e-01,  5.5100e-03,  1.4421e-01,  1.2912e-01,  1.3484e-01]],

         [[ 2.4361e-03,  6.3932e-02,  3.5414e-02, -4.3948e-02, -1.6019e-02],
          [-8.8783e-02, -3.5182e-02,  1.1135e-01,  3.0703e-02,  6.2916e-02],
          [-5.1563e-02,  8.7525e-02, -

In [8]:
model.perform_pruning()

In [9]:
print(list(model.conv1.named_parameters()))

[('bias', Parameter containing:
tensor([ 0.0619, -0.0059,  0.1237, -0.0349,  0.0230, -0.0679,  0.1573, -0.0077,
         0.0054,  0.1314,  0.1008,  0.0664,  0.0991,  0.0481,  0.0851,  0.1861,
        -0.0625, -0.0473,  0.0706,  0.0971, -0.0760,  0.1384,  0.1409,  0.0886,
         0.0103,  0.0090,  0.0345,  0.0358,  0.0429,  0.0703, -0.0790,  0.1181],
       device='cuda:0', requires_grad=True)), ('weight_orig', Parameter containing:
tensor([[[[ 8.7982e-02,  8.5622e-02,  7.1099e-02,  4.3684e-02,  2.9080e-02],
          [ 6.7263e-02,  7.0992e-02,  9.9368e-02,  7.5297e-02,  8.3281e-02],
          [ 1.0704e-01,  7.3422e-02, -4.9580e-02,  1.2928e-01,  1.2822e-01],
          [-6.6067e-03,  7.1147e-02, -7.1086e-02, -9.3603e-03, -2.9341e-02],
          [ 1.2063e-01, -3.8537e-02, -7.5647e-02,  1.0389e-01, -8.6257e-02]],

         [[-8.4184e-02,  7.5236e-02,  8.4671e-02, -1.9000e-02,  4.6655e-02],
          [ 1.2659e-01,  5.6393e-02, -6.3011e-02,  8.5046e-03, -7.7577e-02],
          [ 4.9156e-02

In [10]:
print(list(model.conv1.named_buffers()))

[('weight_mask', tensor([[[[1., 1., 1., 1., 1.],
          [1., 0., 1., 1., 1.],
          [1., 0., 1., 1., 1.],
          [0., 1., 1., 1., 1.],
          [1., 1., 1., 0., 1.]],

         [[0., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 0., 1., 1., 1.],
          [1., 0., 0., 1., 1.],
          [1., 1., 1., 0., 1.]],

         [[1., 1., 1., 0., 1.],
          [1., 0., 1., 1., 1.],
          [1., 1., 0., 1., 1.],
          [1., 1., 0., 0., 1.],
          [1., 1., 1., 1., 1.]]],


        [[[1., 0., 1., 1., 1.],
          [0., 0., 1., 0., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.]],

         [[0., 0., 0., 1., 1.],
          [1., 1., 1., 1., 1.],
          [0., 1., 1., 1., 1.],
          [0., 0., 1., 0., 1.],
          [1., 1., 0., 1., 1.]],

         [[0., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [0., 1., 0., 1., 1.],
          [1., 1., 1., 0., 1.],
          [1., 1., 1., 1., 1.]]],


       

In [11]:
model.adversarial_validation()

10000
Successful attack:8694 Attack count:10000 Percentage:0.8694


13.060000000000006

In [7]:
list(model.fc2.weight.grad)

[Parameter containing:
 tensor([[nan, nan, nan,  ..., nan, nan, nan],
         [nan, nan, nan,  ..., nan, nan, nan],
         [nan, nan, nan,  ..., nan, nan, nan],
         ...,
         [nan, nan, nan,  ..., nan, nan, nan],
         [nan, nan, nan,  ..., nan, nan, nan],
         [nan, nan, nan,  ..., nan, nan, nan]], requires_grad=True),
 Parameter containing:
 tensor([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan], requires_grad=True)]